language: node_js

node_js:
  - 'lts/*'

before_script:
  # lint the files (fail early)
  - npm run security
  # build the docker compose file
  - npm run docker-build
  - docker-compose up -d kuhts-postgres
  - sleep 3
  - npm run create-db
  - npm run docker-migrate-up

script:
  - 'npm run travis'

services:
  - docker

cache:
  directories:
    - node_modules

env:
  global:
    - "DATABASE_URL=postgres://kuhts:password@localhost:3011/kuhts"
    - "REDIS_URL=redis://localhost:3010"
    - "SESSION_SECRET=4fd0aa45-a508-476e-b4e1-73740d684af0"
    - "NODE_ENV=test"
    - "SECURE=false"
    - "NODE_PATH=./"
    - "DEBUG=*,-express*,kuhts,-socket.io*,-eslint*,-babel*,-snapdragon*,-knex*"
